# Generated by Django 4.0.1 on 2022-01-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='N/A', max_length=64),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='N/A', max_length=12),
        ),
    ]
